#!/bin/bash

APP_NAME="My Project Name"
APP_URL="http://localhost"

TIMEZONE="America/Moncton"

DB_ROOT_PASSWORD="root"
DB_DATABASE="laravel"

MAIL_MAILER="smtp"
MAIL_HOST="smtp.mailtrap.io"
MAIL_PORT="2525"
MAIL_USERNAME=null
MAIL_PASSWORD=null
MAIL_ENCRYPTION=null
MAIL_FROM_ADDRESS=null
MAIL_FROM_NAME="My Project Name"
